// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddMovieController from "./add_movie_controller"
application.register("add-movie", AddMovieController)

import WishlistController from "./wishlist_controller"
application.register("wishlist", WishlistController)
